M48
; DRILL file {KiCad (6.0.7)} date Fri Jul 29 13:47:05 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-29T13:47:05-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C6.400
%
G90
G05
T1
X66.62Y-118.11
X66.62Y-135.89
X151.13Y-118.11
X151.13Y-135.89
T2
X96.393Y-117.983
T3
X101.854Y-127.889
T0
M30
